<a href="https://colab.research.google.com/github/dcthyun0308/ESAA/blob/main/0410_%EC%84%B8%EC%85%98_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
# 이전 문제의 조건에 따라 (7, 7) 형상으로 생성합니다.
X = torch.rand(size=(7, 7))

# 결과 확인
print(f"생성된 텐서:\n{X}")
print(f"텐서의 모양: {X.shape}")

생성된 텐서:
tensor([[0.9989, 0.1494, 0.5511, 0.4720, 0.9771, 0.3268, 0.3352],
        [0.8507, 0.6017, 0.0641, 0.7808, 0.7693, 0.0497, 0.1394],
        [0.9560, 0.8124, 0.0722, 0.7611, 0.4577, 0.9726, 0.6093],
        [0.4916, 0.1710, 0.1406, 0.3650, 0.6810, 0.0587, 0.1582],
        [0.3700, 0.8634, 0.3520, 0.4797, 0.7296, 0.1526, 0.0431],
        [0.1868, 0.2299, 0.5940, 0.5755, 0.5850, 0.1383, 0.2362],
        [0.1261, 0.5376, 0.4725, 0.3650, 0.7923, 0.8958, 0.7449]])
텐서의 모양: torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
Y = torch.rand(size=(1, 7))

# Perform matrix multiplication
# (7, 7) @ (1, 7)은 차원이 맞지 않아 에러가 발생합니다.
# 따라서 Y를 전치(Transpose)하여 (7, 1)로 만들어줍니다.
Z = torch.matmul(X, Y.T)

# 결과 확인
print(f"텐서 Y의 모양: {Y.shape}")
print(f"전치된 Y의 모양: {Y.T.shape}")
print(f"행렬 곱 결과 Z의 모양: {Z.shape}")
print(f"\n결과값 Z:\n{Z}")

텐서 Y의 모양: torch.Size([1, 7])
전치된 Y의 모양: torch.Size([7, 1])
행렬 곱 결과 Z의 모양: torch.Size([7, 1])

결과값 Z:
tensor([[2.5882],
        [2.1703],
        [3.2718],
        [1.4195],
        [1.7881],
        [1.7664],
        [2.8082]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)

# Matrix multiply tensors
# tensor_B를 전치(transpose)하여 (7, 1)로 만든 뒤 곱합니다.
output = torch.matmul(tensor_A, tensor_B.T)

# 결과 확인
print(output, output.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU

# GPU 전용 랜덤 시드 설정
torch.cuda.manual_seed(1234)

# 만약 여러 개의 GPU를 사용 중이라면 모든 GPU에 시드를 설정할 때
# torch.cuda.manual_seed_all(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
# 텐서를 생성한 후 .to(device)를 통해 GPU로 보냅니다.
tensor_A = torch.rand(size=(2, 3)).to(device)
tensor_B = torch.rand(size=(2, 3)).to(device)

# 결과 확인
print(tensor_A, tensor_B)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [6]:
# Perform matmul on tensor_A and tensor_B
# (2, 3) @ (3, 2) -> (2, 2) 결과가 나옵니다.
output = torch.matmul(tensor_A, tensor_B.T)

# 결과 확인 (이미지에 나온 것처럼 출력하기 위해 튜플 형태로 작성)
print(output, output.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [7]:
# Find max
max_val = output.max()

# Find min
min_val = output.min()

# 결과 확인
print(f"Maximum value: {max_val}")
print(f"Minimum value: {min_val}")

Maximum value: 0.5617256760597229
Minimum value: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [8]:
# Find arg max
max_idx = output.argmax()

# Find arg min
min_idx = output.argmin()

# 결과 확인
print(f"최댓값의 위치(인덱스): {max_idx}")
print(f"최솟값의 위치(인덱스): {min_idx}")

최댓값의 위치(인덱스): 3
최솟값의 위치(인덱스): 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [9]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_A = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
# squeeze()는 크기가 1인 모든 차원을 제거해줍니다.
tensor_B = tensor_A.squeeze()

# Print out tensors and their shapes
print(tensor_A, tensor_A.shape)
print(tensor_B, tensor_B.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
