<a href="https://colab.research.google.com/github/dcthyun0308/ESAA/blob/main/ESAA_OB_week05_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.1 인공지능, 머신 러닝과 딥러닝

- 인공지능 > 머신 러닝 > 딥러닝

- 머신 러닝과 딥러닝 모두 학습 모델을 제공하여 데이터를 분류할 수 있는 기술. 하지만 접근 방식에 차이가 있음. 머신 러닝은 주어진 데이터를 인간이 먼저 처리함. 딥러닝은 인간이 하던 작업을 생략하고 대량의 데이터를 신경망에 적용하면 컴퓨터가 스스로 분석한 후 답을 찾음.

#1.2 머신 러닝이란

##1.2.1 머신 러닝 학습 과정

- 머신 러닝은 다음 그림과 같이 크게 학습 단계와 예측 단계로 구분할 수 있음. 훈련 데이터를 머신 러닝 알고리즘에 적용하여 학습시키고, 이 학습 결과로 모형이 생성됨. 예측 단계에서는 학습 단계에서 생성된 모형에 데이터를 적용하여 결과를 예측함.

##1.2.2 머신 러닝 학습 알고리즘

- 지도 학습 : 이름에서 알 수 있듯이 정답이 무엇인지 컴퓨터에 알려 주고 학습시키는 방법.

- 비지도 학습 : 정답을 알려 주지 않고 특징이 비슷한 데이터를 클러스터링하여 예측하는 학습 방법.

- 강화 학습 : 분류할 수 있는 데이터가 있는 것도 아니고 데이터가 있다고 해도 정답이 없어서 어렵고 복잡함. 자신의 행동에 대한 보상을 받으며 학습을 진행함.

#1.3 딥러닝이란

- 딥러닝은 인간의 신경망 원리를 모방한 심층 신경망 이론을 기반으로 고안된 머신 러닝 방법의 일종.

##1.3.1 딥러닝 학습 과정

- 데이터 준비, 모델(모형) 정의, 모델(모형) 컴파일, 모델(모형) 훈련, 모델(모형) 예측

##1.3.2 딥러닝 학습 알고리즘

- 지도 학습으로 분류되는 알고리즘을 살펴보자. 이미지 분류는 이미지 또는 비디오상의 객체를 식별하는 컴퓨터 비전 기술. 컴퓨터 비전에서 가장 많이 사용되는 것이 합성곱 신경망이다. 시계열 데이터를 분류할 때 사용되는 것이 순환 신경망이다.

- 비지도 학습으로는 워드 임베딩과 군집이 있음. 군집은 아무런 정보가 없는 상태에서 데이터를 분류하는 방법.

- 전이학습은 사전에 학습이 완료된 모델을 가지고 우리가 원하는 학습에 미세 조정 기법을 이용하여 학습시키는 방법.

#2.1 파이토치 개요

- 파이토치는 2017년 초에 공개된 딥러닝 프레임워크로 루아 언어로 개발되었던 토치를 페이스북에서 파이썬 버전으로 내놓은 것.

##2.1.1 파이토치 특징 및 장점

- 파이토치 특징 : GPU에서 텐서 조작 및 동적 신경망 구축이 가능한 프레임워크

- GPU : 연산 속도를 빠르게 하는 역할

- 텐서 : 파이토치의 데이터 형태, 단일 데이터 형식으로 된 자료들의 다차원 행렬

- 동적 신경망 : 훈련을 반복할 때마다 네트워크 변경이 가능한 신경망을 의미함.

##2.1.2 파이토치의 아키텍처

- 파이토치 API 계층에서는 사용자가 이해하기 쉬운 API를 제공하여 텐서에 대한 처리와 신경망을 구축하고 훈련할 수 있도록 도움.

- 파이토치 엔진은 Autograd C++, Aten C++, JIT C++, Python API로 구성되어 있음.

- 연산 처리는 가장 아래 계층에 속하는 C 또는 CUDA 패키지는 상위의 API에서 할당된 거의 모든 계산을 수행함.

#2.2 파이토치 기초 문법

##2.2.1 텐서 다루기

###텐서 다루기

텐서 생성 및 변환

In [1]:
import torch
print(torch.tensor([[1,2],[3,4]])) # 2차원 형태의 텐서 생성
print(torch.tensor([[1,2],[3,4]], device="cuda:0")) # GPU에 텐서 생성
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64)) # dtype을 이용하여 텐서 생성

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


이번에는 텐서를 ndarray로 변환해 보자.

In [2]:
temp = torch.tensor([[1,2],[3,4]])
print(temp.numpy()) # 텐서를 ndarray로 변환

temp = torch.tensor([[1,2],[3,4]], device="cuda:0")
print(temp.to("cpu").numpy()) # GPU 상의 텐서를 CPU의 텐서로 변환한 후 ndarray로 변환

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


텐서의 인덱스 조작

- 텐서의 자료형 : torch.FloatTensor, torch.DoubleTensor, torch.LongTensor

In [3]:
temp = torch.FloatTensor([1,2,3,4,5,6,7]) # 파이토치로 1차원 벡터 생성
print(temp[0], temp[1], temp[-1])# 인덱스로 접근
print('-------------------------')
print(temp[2:5], temp[4:-1]) # 슬라이스로 접근

tensor(1.) tensor(2.) tensor(7.)
-------------------------
tensor([3., 4., 5.]) tensor([5., 6.])


텐서 연산 및 차원 조작
- 텐서는 넘파이의 ndarray처럼 다양한 수착 연산이 가능하며, GPU를 사용하면 더 빠르게 연산할 수 있음.

In [4]:
v = torch.tensor([1,2,3]) # 길이가 3인 벡터 생성
w = torch.tensor([3,4,6])
print(w - v) # 길이가 같은 벡터 간 뺄셈 연산

tensor([2, 2, 3])


이번에는 텐서의 차원을 조작해 보자.

In [5]:
temp = torch.tensor([
    [1,2],[3,4]]) # 2x2 행렬 생성

print(temp.shape)
print('------------------------')
print(temp.view(4,1)) # 2x2 행렬을 4x1로 변환
print('------------------------')
print(temp.view(-1)) # 2x2 행렬을 1차원 벡터로 변환
print('------------------------')
print(temp.view(1,-1)) # -1은 (1,?)와 같은 의미로 다른 차원으로부터 해당 값을 유차하겠다는 것입니다.
                       # temp의 원소 개수 (2x2=4)를 유치한 채 (1,?)의 형태를 만족해야 하므로 (1,4)가 됩니다.
print('------------------------')
print(temp.view(-1,1)) # 앞에서와 마찬가지로 (?,1)의 의미로 temp의 원소 개수(2x2=4)를 유지한 채 (?,1)의 형태를 만족해야 하므로 (4,1)이 됩니다.

torch.Size([2, 2])
------------------------
tensor([[1],
        [2],
        [3],
        [4]])
------------------------
tensor([1, 2, 3, 4])
------------------------
tensor([[1, 2, 3, 4]])
------------------------
tensor([[1],
        [2],
        [3],
        [4]])


##2.2.2 데이터 준비

###단순하게 파일을 불러와서 사용

In [6]:
!pip install pandas

In [8]:
# import pandas as pd # pandas 라이브러리 호출
# import torch
# data = pd.read('class2.csv') # csv 파일을 불러옵니다.

# x = torch.from_numpy(data['x'].values).unsqueeze(dim=1).float() # CSV 파일의 x 칼럼의 값을 넘파이 배열로 받아 Tensor(dtype)으로 바꾸어 줍니다.
# y = torch.form_numpy(data['y'].values).unsqueeae(dim=1).float() # CSV 파일의 y 칼럼의 값을 넘파이 배열로 받아 Tensor(dtype)으로 바꾸어 줍니다.

In [9]:
# class CustomDataseet(torch.utils.data.Dataset):
#   def __init__(self): # 필요한 변수를 선언하고, 데이터셋의 전처리를 해 주는 함수
#   def __len__(self): # 데이터셋의 값이, 즉, 총 샘플의 수를 가져오는 함수
#   def __getitem__(self, index): # 데이터셋에서 특정 데이터를 가져오는 함수(index번쨰 데이터를 반환하는 함수이며, 이떄 반환되는 값은 텐서의 형태를 취해야 합니다.)

In [10]:
# import pandas as pd
# import torch
# from torch.utils.data import Dataset
# from torch.utils.data import DataLoader

# class CustomDataset(Dataset):
#   def __init__(self, csv_file): # csv_file 파라미터를 통해 데이터셋을 불러옵니다.
#     self.label = pd.read_csv(csv_file)

#   def __len__(self): # 전체 데이터셋의 크기(size)를 반환합니다.
#     return len(self.label)

#   def __getitem__(self, idx): # 전체 x와 y 데이터 중에 해당 idx번째의 데이터를 가져옵니다.
#     sample = torch.tensor(self.label.iloc[idx,0:3]).int()
#     label = torch.tensor(self.label.iloc[idx,3]).int()
#     return smaple, label

# tensor_dataset = CustomDataset('covtype.csv') # 데이터셋으로 covtype.csv를 사용합니다.
# dataset = DataLoader(tensor_dataset, batch_size=4, shuffle=True) # 데이터셋을 torch.utlis.data.DataLoader에 파라미터로 전달합니다.

파이토치에서 제공하는 데이터셋 사용

In [11]:
pip install requests

In [12]:
# import torchvision.transforms as transforms

# mnist_transform = transforms.Compose([
#     transforms.ToTensor(),
#     transforms.Normalize((0.5,),(1.0,))
# ]) # 평균이 0.5, 표준편차가 1.0이 되도록 데이터의 분포를 조정

# from torchvision.datasets import MNIST
# import requests
# download_root = 'MNIAST_DATASET' # 내려받을 경로 지정

# train_dataset = MNIST(download_root, transform=mnist_transform, train=True, download=True) # 훈련 데이터셋
# valid_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True) # 검증 데이터셋
# test_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True) # 테스트 데이터셋

##2.2.3 모델 정의

- 계층 : 모델 또는 모듈을 구성하는 한 개의 계층으로 합성곱충, 선형 계층 등이 있음

- 모듈 : 한 개 이상의 계층이 모여서 구성된 것으로, 모듈이 모여 새로운 모듈을 만들 수 있음

- 모델 : 최종적으로 원하는 네트워크로, 한 개의 모듈이 모델이 될 수도 있음.

단순 신경망을 정의하는 방법

In [13]:
# model = nn.Linear(in_features=1 , out_features=1 , bias=True)

In [14]:
# class MLP(Module):
#   def __init__(self, inputs):
#     super(MLP, self).__init__()
#     self.layer = Linear(inputs, 1) # 계층 정의
#     self.activation = Sigmoid() # 활성화 함수 정의

#   def forward(self, X):
#     X = self.layer(X)
#     X = self.activation(X)
#     return X

Sequential 신경망을 정의하는 방법

In [15]:
import torch.nn as nn
class MLP(nn .Module ):
  def __init__(self):
    super(MLP, self).__init__()
    self.layer1 = nn.Sequential(
        nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5),
        nn.ReLU(inplace=True ),
        nn.MaxPool2d(2))

    self.layer2 = nn.Sequential(
        nn.Conv2d(in_channels=64, out_channels=30, kernel_size=5),
        nn.ReLU(inplace=True),
        nn.MaxPool2d(2))

    self.layer3 = nn.Sequential(
        nn.Linear(in_features=30*5*5, out_features=10, bias=True ),
        nn.ReLU(inplace=True ))

    def forward (self, x):
      x = self.layer1(x)
      x = self.layer2(x)
      x = x.view(x .shape[0] , -1)
      x = self.layer3(x)
      return x
model = MLP() # 모델에 대한 객체 생성

print("Printing children\n-----------------------")
print(list(model.children()))
print("\n\nPrinting Modules\n-----------------------")
print(list(model.modules()))

Printing children
-----------------------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
-----------------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
    (0): Linear(in_features=

함수로 신경망을 정의하는 방법

In [16]:
def MLP(in_features=1, hidden_features=20, out_features=1):
  hidden = nn.Linear( in_features=in_features, out_features=hidden_features,
                     bias=True )
  activation = nn.ReLU()
  output = nn.Linear(in_features=hidden_features, out_features=out_features,
                     bias=True )
  net = nn.Sequential(hidden , activation, output)
  return net

##2.2.4 모델의 파라미터 정의

- 손실 함수 : 학습하는 동안 출력과 실제 값(정답) 사이의 오차를 측정함.

- 옵티마이저 : 데이터와 손실 함수를 바탕으로 모델의 업데이트 방법을 결정함.

- 학습률 스케줄러 : 미리 지정한 횟수의 에포크를 지날 때마다 지날 때마다 학습률을 감소시켜줌.

- 지표 : 훈련과 테스트 단계를 모니터링함.

In [17]:
# from torch.optim import optimizer
# criterion = torch.nn .MSELoss()
# optimizer = torch.optim.SGD(model.parameters() , 1r=0.01, momentum=0.9)
# schedu1er = torch.optim.lr_schedu1er.LambdaLR(optimizer=optimizer,
#                                               1r_lambda=lambda epoch: 0.95 ** epoch)
# for epoch in range (1 , 100+1): # 에포크 수만큼 데이터를 반복하여 처리
#   for x, y in dataloader: # 배치 크기만큼 데이터를 가져와서 학습 진행
#     optimizer.zero_grad()
# 1oss_fn(model(x) , y) .backward()
# optimizer.step()
# schedu1er.step()

##2.2.5 모델 훈련

In [18]:
# for epoch in range(100):
#   yhat = model(x_train)
#   loss = criterion(yhat, y_train)
#   optimizer. zero_9rad() # 오차가 중칩적으로 쌓이지 않도록 초기화
#   loss.backward()
#   optimizer.step()

##2.2.6 모델 평가

In [19]:
pip install torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 59.5 MB/s eta 0:00:00


In [20]:
import torch
import torchmetrics

preds = torch.randn(10, 5).softmax(dim=-1)
target = torch.randint(5, (10,))

acc = torchmetrics.functional.accuracy(preds, target,  task='multiclass', num_classes=5) # 모델을 평가하기 위해 torchmetrics.fenctional.accuracy 이용

In [21]:
import torch
import torchmetrics
metric = torchmetrics . Accuracy(task='multiclass', num_classes=5) # 모댈 평가(정확도) 초기화

n_batches = 10
for i in range(n_batches):
  preds = torch.randn(10, 5).softmax(dim=-1)
  target = torch.randint(5, (10,))

  acc = metric(preds, target)
  print(f"Accuracy on batch {i}: {acc}") # 현재 배치에서 모델 평가(정확도)

acc = metric.compute()
print (f"Accuracy on all data: {acc}") # 모든 배치에서 모델 평가(정확도)

Accuracy on batch 0: 0.30000001192092896
Accuracy on batch 1: 0.20000000298023224
Accuracy on batch 2: 0.10000000149011612
Accuracy on batch 3: 0.10000000149011612
Accuracy on batch 4: 0.20000000298023224
Accuracy on batch 5: 0.30000001192092896
Accuracy on batch 6: 0.4000000059604645
Accuracy on batch 7: 0.10000000149011612
Accuracy on batch 8: 0.699999988079071
Accuracy on batch 9: 0.10000000149011612
Accuracy on all data: 0.25


##2.2.7 훈련 과정 모니터링

In [22]:
# pip install tensorboard

In [23]:
# import torch
# from torch.uti15.tensorboard import SummaryWriter
# writer = SummaryWriter("chap02/tensorboard" ) # 모니터링에 필요한 값들이 저장될 위치

# for epoch in range(num_epoch5):
#   model.train() # 학습 모드로 전환(dropout=True)
#   batch_loss = 0.0

#   for i , (x, y) in enumerate (dataloader):
#     X, Y = x.to(device).f10at(), y.to(device).f1oat()
#     output5 = model(x)
#     loss = criterion(output5, y)
#     writer. add_Sca1ar( "Loss" , loss , epoch) # 스칼라 값(오차)을 기록
#     optimizer.zero_grad()
#     loss.backward()
#     optimizer.step()

# writer.close() # SummaryWriter가 더 이상 필요하지 않으면 close( ) 메서드 호출

In [24]:
# tensorboard --logdir = tensorboard --port-6006