<a href="https://colab.research.google.com/github/dcthyun0308/ESAA/blob/main/ESAA_YB_week01_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 머신러닝
- 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법

- 분류 : 지도학습, 비지도학습, 강화학습
  - 지도학습 : 분류, 회귀, 추천 시스템, 시각/음성 감지/인지, 텍스트분석, NLP
  - 비지도학습 : 클러스터링, 차원 축소, 강화학습

- 단점 : 데이터에 매우 의존적임(좋은 품질의 데이터를 갖추지 못한다면 머신러닝의 수행 결과도 좋을 수 없음)

- 파이썬과 R 기반의 머신러닝 비교 : 파이썬과 R에 비해서 C/C++/JAVA는 개발 생산성이 떨어지고 지원 패키지와 생태계가 활발하지 않음

# 파이썬 머신러닝을 구성하는 주요 패키지
- 머신러닝 패키지(사이킷런), 행렬/선형대수/통계 패키지(넘파이,사이파이), 데이터 핸들링(판다스), 시각화(맷플롯립, 시본)

# 넘파이
- 선형대수 기반 프로그램 관련 대표 패키지

넘파이 ndarray 개요


In [2]:
import numpy as np

- as np를 추가해 약어로 모듈을 표현해주는 게 관례

- 넘파이의 기반 데이터 타입인 ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성함 --> 넘파이의 array() 함수는 다양한 인자를 입력받아서 ndarray로 변환하는 기능을 수행




In [3]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],[2,3,4]])
print('array2 type:', type(array2))
print('array2 arrat 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 arrat 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [5]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


- ndarray의 데이터 타입

In [6]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


리스트는 서로 다른 데이터 타입을 가질 수 있지만, ndarray은 같은 데이터 타입만 가능하다고 했는데, 만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용함
ex) int형이 문자열 값으로 변환, int형과 float형 섞여있는경우 float 따라감

In [7]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


ndarray 내 데이터값의 타입 변경도 astype() 메서드를 이용해 할 수 있음

In [10]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


- ndarray를 편리하게 생성하기 - arange, zeros, ones

arrange() : 파이썬 표준 함수 range()와 유사한 기능, 0부터 함수 인자 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환, default 함수 인자는 stop값임

In [11]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


zeros() : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환

ones() : 함수 인자로 튜플 형태의 shape 값을 1로 채운 해당 shape를 가진 ndarray를 반환

함수 인자로 dtype을 정해주지 않으면 default로 float64 형의 데이터로 ndarray

In [13]:
zero_array = np.zeros((3, 2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


- ndarray의 차원과 크기를 변경하는 reshape()

reshape() 메서드는 ndarray를 특정 차원 및 크기로 변환함

In [14]:
array1 = np.arange(10)
print('array1:|n', array1)

array2 = array1.reshape(2,5)
print('array2:|n', array2)

array3 = array1.reshape(5,2)
print('array3:|n', array3)

array1:|n [0 1 2 3 4 5 6 7 8 9]
array2:|n [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:|n [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


reshape()는 지정된 사이즈로 변경이 불가능하면 오류가 발생함
ex) (10,) 데이터를 (4,3) shape 형태로 변경할 수 없음

In [15]:
array1.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)

reshape()를 실전에서 사용하는 경우는 인자를 -1을 적용하는경우, -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환

In [16]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


물론 -1을 사용하더라도 호환 될 수 없는 형. 태는 변환활 수 없음
ex) reshape(-1, 4)

In [17]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [18]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:|n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:|n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarrat로 변환
array6 = array1.reshape(-1, 1)
print('array6:|n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:|n [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:|n [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:|n [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


- 넘파이의 nadarry의 데이터 세트 선택하기-인덱싱
 1. 특정한 데이터만 추출
 2. 슬라이싱
 3. 팬시 인덱싱
 4. 불린 인덱싱

단일 값 추출
- 1개의 데이터값을 선택하려면 ndarrat 객체에 해당하는 위치의 인덱스 값을 []안에 입력하면 됨

In [19]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [20]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [21]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [22]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


- 슬라이싱
 -':' 기호를 이용해 데이터를 추출

In [23]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


1. ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주
2. ':' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주
3. ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주

In [24]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


2차원 ndarray - 1차원 ndarray에서의 슬라이싱과 유사, 단지 콤마(,)로 로우와 칼럼 인덱스를 지칭하는 부분만 다름

In [25]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:|n', array2d)

print('array2d[0:2, 0:2]|n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]|n', array2d[1:3, 0:3])
print('array2d[1:3, :]|n', array2d[1:3, :])
print('array2d[:, :]|n', array2d[:, :])
print('array2d[:2, 1:]|n', array2d[:2, 1:])
print('array2d[:2, 0]|n', array2d[:2, 0])

array2d:|n [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]|n [[1 2]
 [4 5]]
array2d[1:3, 0:3]|n [[4 5 6]
 [7 8 9]]
array2d[1:3, :]|n [[4 5 6]
 [7 8 9]]
array2d[:, :]|n [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]|n [[2 3]
 [5 6]]
array2d[:2, 0]|n [1 4]


2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환함

In [27]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape;', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape; (3,) array2d[1] shape: (3,)


- 팬시 인덱싱 : 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [30]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] =>', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] =>', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] =>', array5.tolist())

array2d[[0, 1], 2] => [3, 6]
array2d[[0, 1], 0:2] => [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


- 불린 인덱싱 : 조건 필터링과 검색을 동시에 할 수 있기 때문에 매주 자주 사용되는 인덱싱 방식

In [31]:
array1d = np.arange(start=1, stop=10)

# [] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [34]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [37]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 ：', array3)


불린 인덱스로 필터링 결과 ： [6 7 8 9]


In [38]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


- 행렬의 정렬 - sort()와 argsort()

행렬 정렬
넘파이의 행렬 정렬은 np.sort()와 같이 넘파이에서 sort()를 호출하는 방식과 ndarray.sort()와 같이 행렬 자체에서 sort()를 호출하는 방식있음

In [41]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np,sort() 호출 후 원본 행렬:', org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np,sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [42]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [46]:
array2d = np.array([[8, 12], [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:|n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:|n', sort_array2d_axis1)

로우 방향으로 정렬:|n [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:|n [[ 8 12]
 [ 1  7]]


- 정렬된 행렬의 인덱스를 반환하기

In [47]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [49]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [50]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


- 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

    행렬 내적은 행렬 곱

In [51]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:|n', dot_product)

행렬 내적 결과:|n [[ 58  64]
 [139 154]]


- 전치 행렬 : 원 행렬에서 행과 열 위치를 교환한 행렬을 그 행렬이라 함

In [53]:
A = np.array([[1, 2], [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:|n', transpose_mat)

A의 전치 행렬:|n [[1 3]
 [2 4]]
